"""init

Revision ID: eef726edd7b6
Revises: 
Create Date: 2025-07-05 15:00:07.188198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef726edd7b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyvalue',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_keyvalue_deleted_at'), 'keyvalue', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_keyvalue_key'), 'keyvalue', ['key'], unique=False)
    op.create_index(op.f('ix_keyvalue_updated_at'), 'keyvalue', ['updated_at'], unique=False)
    op.create_table('pixel_events',
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('pixel_id', sa.Integer(), nullable=False),
    sa.Column('stake_amount', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('effective_stake_amount', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('log_index', 'timestamp', 'pixel_id')
    )
    op.create_index(op.f('ix_pixel_events_chain_id'), 'pixel_events', ['chain_id'], unique=False)
    op.create_index(op.f('ix_pixel_events_deleted_at'), 'pixel_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pixel_events_log_index'), 'pixel_events', ['log_index'], unique=False)
    op.create_index(op.f('ix_pixel_events_owner'), 'pixel_events', ['owner'], unique=False)
    op.create_index(op.f('ix_pixel_events_pixel_id'), 'pixel_events', ['pixel_id'], unique=False)
    op.create_index(op.f('ix_pixel_events_timestamp'), 'pixel_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_pixel_events_updated_at'), 'pixel_events', ['updated_at'], unique=False)
    op.create_table('pixels',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('stake_amount', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('effective_stake_amount', sa.Numeric(precision=78, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('hash', sa.String(), server_default='0x0000000000000000000000000000000000000000000000000000000000000000', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pixels_color'), 'pixels', ['color'], unique=False)
    op.create_index(op.f('ix_pixels_deleted_at'), 'pixels', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pixels_id'), 'pixels', ['id'], unique=False)
    op.create_index(op.f('ix_pixels_owner'), 'pixels', ['owner'], unique=False)
    op.create_index(op.f('ix_pixels_updated_at'), 'pixels', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pixels_updated_at'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_owner'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_id'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_deleted_at'), table_name='pixels')
    op.drop_index(op.f('ix_pixels_color'), table_name='pixels')
    op.drop_table('pixels')
    op.drop_index(op.f('ix_pixel_events_updated_at'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_timestamp'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_pixel_id'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_owner'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_log_index'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_deleted_at'), table_name='pixel_events')
    op.drop_index(op.f('ix_pixel_events_chain_id'), table_name='pixel_events')
    op.drop_table('pixel_events')
    op.drop_index(op.f('ix_keyvalue_updated_at'), table_name='keyvalue')
    op.drop_index(op.f('ix_keyvalue_key'), table_name='keyvalue')
    op.drop_index(op.f('ix_keyvalue_deleted_at'), table_name='keyvalue')
    op.drop_table('keyvalue')
    # ### end Alembic commands ###
